#pragma once
const char INDEX_HTML[] PROGMEM = R"rawliteral(
<!doctype html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>ESP32 Framework</title>
<style>body{font-family:Arial;margin:16px;background:#101622;color:#eaf0ff}.tabs{display:flex;gap:8px;flex-wrap:wrap}.tabs button{padding:8px 14px;border:0;border-radius:8px;cursor:pointer}.tabs button.active{background:#5f88ff;color:#fff}.card{background:#1b2333;padding:16px;border-radius:12px;margin-top:12px}.drop{border:2px dashed #5f88ff;padding:24px;text-align:center;border-radius:10px}.progress{width:100%;height:18px;background:#2a3447;border-radius:10px;overflow:hidden}.bar{width:0;height:100%;background:#43d17d}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:8px}.kpi{background:#131b2b;border-radius:8px;padding:8px}.panel{display:none}.panel.active{display:block}#termView{width:100%;min-height:260px;background:#060a12;color:#49f27f;border-radius:8px;padding:10px;box-sizing:border-box;font-family:monospace;white-space:pre-wrap;overflow:auto}#termInput{width:100%;box-sizing:border-box;margin-top:8px;border-radius:8px;border:1px solid #334;background:#0f1522;color:#fff;padding:8px;resize:vertical;min-height:96px;font-family:monospace}input{background:#0f1522;color:#fff;border:1px solid #334;border-radius:8px;padding:8px}</style>
</head><body><h2>ESP32 Framework</h2>
<div class="tabs"><button id="tab-ota" class="active">OTA</button><button id="tab-term">Web Terminal</button><button id="tab-cred">Credential</button><button disabled>Mesh</button><button disabled>ESP-NOW</button><button disabled>URL</button></div>
<div id="panel-ota" class="panel active"><div class="card"><h3>OTA Firmware Update</h3><div id="drop" class="drop">Drag & drop firmware <b>.bin</b> or choose file<br><input id="fw" type="file" accept=".bin"/></div><p><button id="btnUpload">Update Firmware</button> <button id="btnRollback">Rollback</button> <button id="btnReboot">Reboot</button></p><div class="progress"><div id="uploadBar" class="bar"></div></div><small id="msg">Idle</small></div><div class="card"><h3>Device Info</h3><div id="info" class="grid"></div><div>Heap:<div class="progress"><div id="heapBar" class="bar"></div></div></div><div>Flash:<div class="progress"><div id="flashBar" class="bar"></div></div></div></div></div>
<div id="panel-term" class="panel"><div class="card"><h3>Web Terminal</h3><div id="termView"></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:8px;"><button id="btnTermClear" type="button">Clear</button><button id="btnTermDownload" type="button">Download</button></div><textarea id="termInput" rows="4" placeholder="ketik command (Enter kirim, Shift+Enter baris baru, max 4092 byte)"></textarea><small id="termMeta">TX/RX max 4092 byte</small></div></div>
<div id="panel-cred" class="panel"><div class="card"><h3>Credential WiFi</h3><p><button id="btnCredLoad">Load</button> <button id="btnCredSave">Save</button> <small id="credMsg"></small></p></div><div class="card"><label><input id="staEnabled" type="checkbox"/> Enable STA</label><h4>STA Mode</h4><p style="display:flex;gap:8px;"><input id="staSsid" placeholder="STA SSID" style="flex:1;"/><button id="btnScan">Scan</button></p><input id="staPassword" placeholder="STA Password" type="password" style="width:100%;"/><div id="scanResults" style="margin-top:8px;"></div></div><div class="card"><label><input id="apEnabled" type="checkbox"/> Enable AP</label><h4>AP Mode</h4><input id="apSsid" placeholder="AP SSID" style="width:100%;"/><input id="apPassword" placeholder="AP Password" type="password" style="width:100%;margin-top:8px;"/><p><input id="apChannel" type="number" min="1" max="13" value="1"/> Channel</p><label><input id="apBroadcast" type="checkbox" checked/> Broadcast SSID</label><p><small>Jika STA+AP aktif, channel AP mengikuti channel STA.</small></p></div></div>
<script>
let selectedFile=null,activeTab='ota',statusTimer=null,termTimer=null;const $=id=>document.getElementById(id),msg=t=>$('msg').textContent=t;
function setTab(tab){activeTab=tab;$('tab-ota').classList.toggle('active',tab==='ota');$('tab-term').classList.toggle('active',tab==='term');$('tab-cred').classList.toggle('active',tab==='cred');$('panel-ota').classList.toggle('active',tab==='ota');$('panel-term').classList.toggle('active',tab==='term');$('panel-cred').classList.toggle('active',tab==='cred');startServicesForTab()}['ota','term','cred'].forEach(t=>$('tab-'+t).addEventListener('click',()=>setTab(t)));
function stopAllServices(){if(statusTimer){clearInterval(statusTimer);statusTimer=null}if(termTimer){clearInterval(termTimer);termTimer=null}}
function startServicesForTab(){stopAllServices();if(activeTab==='ota'){refreshStatus();statusTimer=setInterval(refreshStatus,2000)}else if(activeTab==='term'){pollTerminal();termTimer=setInterval(pollTerminal,300)}else if(activeTab==='cred'){loadCredential()}}
function ensureBin(file){return file&&file.name.toLowerCase().endsWith('.bin')}$('fw').addEventListener('change',e=>{selectedFile=e.target.files[0];msg(ensureBin(selectedFile)?`Ready: ${selectedFile.name}`:'File must be .bin')});$('drop').addEventListener('dragover',e=>e.preventDefault());$('drop').addEventListener('drop',e=>{e.preventDefault();selectedFile=e.dataTransfer.files[0];msg(ensureBin(selectedFile)?`Ready: ${selectedFile.name}`:'File must be .bin')});
$('btnUpload').addEventListener('click',()=>{if(!ensureBin(selectedFile))return msg('Please select valid .bin file');const fd=new FormData();fd.append('update',selectedFile);const xhr=new XMLHttpRequest();xhr.upload.onprogress=e=>{$('uploadBar').style.width=`${e.lengthComputable?Math.round((e.loaded/e.total)*100):0}%`;msg('Uploading')};xhr.onload=()=>msg(xhr.status===200?'Upload done, device may reboot':`Upload failed ${xhr.status}`);xhr.open('POST','/api/update');xhr.send(fd)});
async function post(url){const r=await fetch(url,{method:'POST'});const j=await r.json();msg(j.message||'done')}$('btnRollback').addEventListener('click',()=>post('/api/rollback'));$('btnReboot').addEventListener('click',()=>post('/api/reboot'));
function dash(v){return(v===undefined||v===null||v==='')?'-':v}function bar(id,used,total){$(id).style.width=`${total>0?Math.min(100,Math.round((used/total)*100)):0}%`}
async function refreshStatus(){const r=await fetch('/api/status');const s=await r.json();$('info').innerHTML=[['Firmware',s.firmwareVersion],['Framework',s.frameworkVersion],['Hardware',s.hardwareVersion],['Device ID',s.deviceId],['Runtime (min)',s.runTimeMinutes],['Power On',s.powerOn],['Suhu',s.temperature],['Tegangan',s.voltage]].map(([k,v])=>`<div class='kpi'><b>${k}</b><br>${dash(v)}</div>`).join('');bar('heapBar',s.heapUsed||0,s.heapTotal||0);bar('flashBar',s.flashUsed||0,s.flashTotal||0)}
function appendTerm(text){if(!text)return;const view=$('termView');view.textContent+=text;if(view.textContent.length>40000)view.textContent=view.textContent.slice(-40000);view.scrollTop=view.scrollHeight}
async function pollTerminal(){const r=await fetch('/api/webterm/poll');const j=await r.json();appendTerm(j.data||'')}
$('btnTermClear').addEventListener('click',()=>{$('termView').textContent=''});$('btnTermDownload').addEventListener('click',()=>{const blob=new Blob([$('termView').textContent||''],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`webterm-${Date.now()}.log`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)});
$('termInput').addEventListener('keydown',async e=>{if(e.key!=='Enter')return;if(e.shiftKey)return;e.preventDefault();const data=e.target.value;e.target.value='';if(!data)return;const enc=new TextEncoder().encode(data);if(enc.length>4092)return appendTerm('\n[web] input > 4092 byte ditolak\n');await fetch('/api/webterm/write',{method:'POST',headers:{'Content-Type':'text/plain'},body:data})});
function setCredMsg(t){$('credMsg').textContent=t}function setCredCardState(){const sta=$('staEnabled').checked,ap=$('apEnabled').checked;['staSsid','staPassword','btnScan'].forEach(i=>$(i).disabled=!sta);['apSsid','apPassword','apChannel','apBroadcast'].forEach(i=>$(i).disabled=!ap)}
$('staEnabled').addEventListener('change',setCredCardState);$('apEnabled').addEventListener('change',setCredCardState);
function applyCredentialToForm(c){$('staEnabled').checked=!!c.staEnabled;$('apEnabled').checked=!!c.apEnabled;$('staSsid').value=c.staSsid||'';$('staPassword').value=c.staPassword||'';$('apSsid').value=c.apSsid||'';$('apPassword').value=c.apPassword||'';$('apChannel').value=c.apChannel||1;$('apBroadcast').checked=c.apBroadcast!==false;setCredCardState()}
async function loadCredential(){const r=await fetch('/api/credential');const j=await r.json();if(j.credential)applyCredentialToForm(j.credential)}
function collectCredential(){return{staEnabled:$('staEnabled').checked,apEnabled:$('apEnabled').checked,staSsid:$('staSsid').value,staPassword:$('staPassword').value,apSsid:$('apSsid').value,apPassword:$('apPassword').value,apChannel:Number($('apChannel').value||1),apBroadcast:$('apBroadcast').checked}}
$('btnCredLoad').addEventListener('click',loadCredential);$('btnCredSave').addEventListener('click',async()=>{const r=await fetch('/api/credential',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({credential:collectCredential()})});const j=await r.json();setCredMsg(j.message||(j.ok?'saved':'failed'))});
$('btnScan').addEventListener('click',async()=>{setCredMsg('Scanning...');const r=await fetch('/api/credential/scan');const j=await r.json();$('scanResults').innerHTML=(j.networks||[]).map(n=>`<button type='button' class='kpi' style='display:block;width:100%;text-align:left;margin-top:4px;' data-ssid="${(n.ssid||'').replace(/"/g,'&quot;')}">${n.ssid||'(hidden)'} | ${n.bssid||'-'} | RSSI ${n.rssi??'-'}</button>`).join('')||'<small>Tidak ada SSID ditemukan</small>';[...$('scanResults').querySelectorAll('button[data-ssid]')].forEach(b=>b.addEventListener('click',()=>{$('staSsid').value=b.dataset.ssid||''}));setCredMsg('Scan selesai')});
startServicesForTab();
</script></body></html>
)rawliteral";
